# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mm <- function(A, B) {
    .Call(`_optimalclpm_mm`, A, B)
}

mmm <- function(A, B, C) {
    .Call(`_optimalclpm_mmm`, A, B, C)
}

mmmm <- function(A, B, C, D) {
    .Call(`_optimalclpm_mmmm`, A, B, C, D)
}

minv <- function(A) {
    .Call(`_optimalclpm_minv`, A)
}

